#Application URL
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

#Brower configuration
browser = chrome

#Credentials
username = admin
password = admin123

#Implicit wait
implicitWait = 10

#explicit wait
explicitWait = 20